// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'xcomm';
  static const String PROJECT_VERSION = '0.0.1';
  static const String MY = 'assets/flags/my.png';
  static const String SG = 'assets/flags/sg.png';
  static const String ICO_CHECK = 'assets/svg/ico-check.svg';
  static const String ICO_WARNING = 'assets/svg/ico-warning.svg';
}
